### ISSUE TITLE
Enhance NFT module

### ISSUE THREAD

**Issue by chengwenxi** [irisnet/irismod#183]
## Summary

There are some differences between NFT and [ERC721](https://eips.ethereum.org/EIPS/eip-721), now let them converge. Here are some rough ideas:

* Add `Approve` function, NFT can be transferred from the owner or the approved address.
* `Denom` adds `update_restricted` field, the owner can edit the NFT only when the `update_restricted` is true.
* `Denom` adds `Symbol` field which is equivalent to `ERC721Metadata.symbol()`.
* Only the `Denom` creator can mint NFT, or it can be optional. Add `mint_restricted` for it.

**Comment by mindcarver** [comment]
The actual work is as follows:
1. Denom adds Symbol field which is equivalent to ERC721Metadata.symbol().
2. Denom add MintRestricted filed , MintRestricted is true means that only Denom owners can issue NFTs under this category, false means anyone can
3. Denom add  UpdateRestricted filed,  UpdateRestricted is true means that no one in this category can update the NFT, false means that only the owner of this NFT can update
4. Add transferDenom method that the owner of the NFT classification can transfer the ownership of the NFT classification to others
